#!/bin/sh

$ECHO "KNewClass v0.3 (C) 1999 Kurt Granroth <granroth@kde.org>";
$ECHO;

# STEP 1: INITIALIZATION is done in the main module

###########################################################################
#
# STEP 2:  PROJECT INFORMATION
#
# These routines gather information about the upcoming app.  You shouldn't
# have to change these at all
#
###########################################################################

# Get the class name
unset CLASS_NAME;
while [ ! $CLASS_NAME ];
do
	$ECHO "What is the class name [default: KMyClass]";
	$ECHO ": \c";
	read CLASS_NAME;

	if [ ! "$CLASS_NAME" ];
	then
		CLASS_NAME="KMyClass";
		$ECHO "Going with default name '$CLASS_NAME'";
	fi
done
$ECHO;

# Create some variations
CLASS_NAME_UC=`$ECHO $CLASS_NAME | tr a-z A-Z`;
CLASS_NAME_LC=`$ECHO $CLASS_NAME | tr A-Z a-z`;

# Get the parent class name
unset PARENT;
$ECHO "What is the parent class name [default: NO PARENT CLASS]";
$ECHO ": \c";
read PARENT;
$ECHO;

if [ "$PARENT" ];
then
	PARENT_LC=`$ECHO $PARENT | tr A-Z a-z`;
fi

# Get the source file
unset CPP_FILE;
while [ ! $CPP_FILE ];
do
	$ECHO "What is its source file [default: $CLASS_NAME_LC.cpp]";
	$ECHO ": \c";
	read CPP_FILE;

	if [ ! $CPP_FILE ];
	then
		CPP_FILE="$CLASS_NAME_LC.cpp";
		$ECHO "Going with default name '$CPP_FILE'";
	fi
done
$ECHO;

# Get the header file
unset HDR_FILE;
while [ ! $HDR_FILE ];
do
	$ECHO "What is its header file [default: $CLASS_NAME_LC.h]";
	$ECHO ": \c";
	read HDR_FILE;

	if [ ! $HDR_FILE ];
	then
		HDR_FILE="$CLASS_NAME_LC.h";
		$ECHO "Going with default name '$HDR_FILE'";
	fi
done
$ECHO;

# Get the author's name
unset AUTHOR;
while [ ! "$AUTHOR" ];
do
	if [ "$DEFAULT_AUTHOR" ];
	then
		$ECHO "What is your name [default: $DEFAULT_AUTHOR]";
	else
		$ECHO "What is your name [no default]";
	fi
	$ECHO ": \c";
	read AUTHOR;

	if [ "$DEFAULT_AUTHOR" -a ! "$AUTHOR" ];
	then
		AUTHOR="$DEFAULT_AUTHOR";
		$ECHO "Going with default author '$AUTHOR'";
	fi
done
$ECHO;

# Get the author's email
unset EMAIL;
while [ ! "$EMAIL" ];
do
	if [ "$DEFAULT_EMAIL" ];
	then
		$ECHO "What is your email address [default: $DEFAULT_EMAIL]";
	else
		$ECHO "What is your email address [no default]";
	fi
	$ECHO ": \c";
	read EMAIL;

	if [ "$DEFAULT_EMAIL" -a ! "$EMAIL" ];
	then
		EMAIL="$DEFAULT_EMAIL";
		$ECHO "Going with default email address '$EMAIL'";
	fi
done
$ECHO;

# Verify that everything is grand
$ECHO;
$ECHO "Here is what I have:";
$ECHO "The class: $CLASS_NAME";
$ECHO "Installed in: $CPP_FILE $HDR_FILE";
if [ "$PARENT" ];
then
	$ECHO "Parent class: $PARENT";
fi
$ECHO "Author: $AUTHOR <$EMAIL>";
$ECHO;
$ECHO "Is this correct (Y/n)? ";
$ECHO ": \c";
read Y_N;
if [ $Y_N -a $Y_N = 'n' ];
then
	$ECHO "AUGH!  Well, try again.";
	exit 0;
fi
$ECHO;

$ECHO "OK, Here we go!!";

###########################################################################
#
# STEP 3:  GENERATE APP-SPECIFIC FILES
#
# This step will create all files that are specific to the new app.
#
###########################################################################

for EXE_FILE in $KNEWCLASS_FILES;
do
	. $SHARE_DIR/knewclass/$EXE_FILE || exit 1;
done

$ECHO "DONE!";
